# Generated by Django 6.0.3 on 2026-04-28 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(help_text='Matrícula da pessoa', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(regex='\\d{11}')], verbose_name='CPF')),
                ('nome', models.CharField(help_text='Nome da pessoa', max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
    ]
