# Generated by Django 6.0.3 on 2026-04-28 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código do prédio', max_length=2, unique=True, validators=[django.core.validators.RegexValidator(regex='[A-Z]|[a-z]{1,2}')], verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Prédio',
                'verbose_name_plural': 'Prédios',
            },
        ),
    ]
