# Generated by Django 6.0.3 on 2026-03-31 23:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predio',
            name='codigo',
            field=models.CharField(help_text='Código do prédio', max_length=2, unique=True, validators=[django.core.validators.RegexValidator(regex='[A-Z]|[a-z]{1,2}')], verbose_name='Código'),
        ),
    ]
