# Generated by Django 6.0.3 on 2026-04-28 23:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número da Sala', max_length=3, validators=[django.core.validators.RegexValidator(regex='\\b[1-9]{1}[0-9]{1}[1-9]{1}\\b')], verbose_name='Número')),
                ('nome', models.CharField(max_length=6, unique=True)),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predios.predio')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
    ]
