# Generated by Django 6.0.3 on 2026-04-24 00:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_alter_emprestimo_fim_alter_emprestimo_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='fim',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
