# Generated by Django 6.0.3 on 2026-04-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0004_alter_emprestimo_fim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='fim',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
