# Generated by Django 6.0.3 on 2026-04-02 23:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predios', '0002_alter_predio_codigo'),
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=9, unique=True)),
                ('numero', models.CharField(help_text='Número da Chave', max_length=3, validators=[django.core.validators.RegexValidator(regex='\\b[0-9]{2}\\b')], verbose_name='Número')),
            ],
            options={
                'verbose_name': 'Chave',
                'verbose_name_plural': 'Chaves',
            },
        ),
        migrations.CreateModel(
            name='ChavePredio',
            fields=[
                ('chave_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chave.chave')),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predios.predio')),
            ],
            options={
                'verbose_name': 'Chave de prédio',
                'verbose_name_plural': 'Chaves de prédios',
            },
            bases=('chave.chave',),
        ),
        migrations.CreateModel(
            name='ChaveSala',
            fields=[
                ('chave_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chave.chave')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salas.sala')),
            ],
            options={
                'verbose_name': 'Chave de sala',
                'verbose_name_plural': 'Chaves de salas',
            },
            bases=('chave.chave',),
        ),
    ]
