# Generated by Django 6.0.3 on 2026-04-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chave',
            name='disponivel',
            field=models.BooleanField(default=True, verbose_name='Disponivel'),
        ),
    ]
